export const designSystemAssets = {
  brand: {
    mark: "/brand/promptraise-mark.svg",
  },
  hero: {
    video: "/videos/hero-loop.mp4",
    poster: "/images/hero-poster.png",
  },
  figma: {
    auditArrow: "/figma/inner-frame-1.svg",
    stats: {
      mask: "/figma/logo-shape.svg",
      ellipse1: "/figma/decorative-shape.svg",
      ellipse2: "/figma/arrow.svg",
      ellipse3: "/figma/arrow-2.svg",
      ellipse4: "/figma/vector.svg",
      ellipse5: "/figma/separator-line.svg",
    },
    team: {
      teamCardTop: "/figma/team-maxim.png",
      teamCardTop2: "/figma/team-zain.png",
      overlayVector: "/figma/team-overlay-main.svg",
      overlayVector2: "/figma/team-overlay-maxim.svg",
      overlayVector3: "/figma/team-overlay-zain.svg",
      twitter: "/figma/icon-twitter.svg",
      linkedin: "/figma/icon-linkedin.svg",
      ellipse: "/figma/team-ellipse.svg",
      cicadaLogo: "/figma/backed-cicada.svg",
      strategyLogo: "/figma/backed-strategy.svg",
      bgMask: "/figma/team-bg-mask.svg",
      bgLayer1: "/figma/team-bg-layer1.svg",
      bgLayer2: "/figma/team-bg-layer2.svg",
      bgLayer3: "/figma/team-bg-layer3.svg",
      badgeLine: "/figma/team-badge-line.svg",
      badgeMark1: "/figma/team-badge-mark-1.svg",
      badgeMark2: "/figma/team-badge-mark-2.svg",
      photoMaxim: "/figma/team-photo-maxim.png",
      photoZain: "/figma/team-photo-zain.png",
    },
  },
} as const;
